---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: "Gitlab + Jenkins + Nexus"
    instance_type_light: t2.micro
    instance_type_heavy: t2.medium
    security_group: sg-4b9f0b2d
    image: ami-d2c924b2
    region: us-west-2
    vpc_subnet_id: subnet-1832f040
    tower_hostname: "ec2-52-89-92-249.us-west-2.compute.amazonaws.com"
    tower_hostkey: "8013c2680a5c7d42eb3f273131581bab"
    tower_provision_job_id: 9
  tasks:
    - add_host: name="{{ tower_hostname }}"
    - name: Launch GitLab instance
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type_heavy }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          role: gitlab
          Name: GitLab
        count_tag: 
          role: gitlab
        exact_count: 1
      register: ec2
    - name: Launch Jenkins instance
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type_heavy }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          role: jenkins
          Name: Jenkins
        count_tag: 
          role: jenkins
        exact_count: 1
      register: ec2
    - name: Launch Docker Registry instance
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type_light }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          role: docker
          Name: Docker Registry
        count_tag: 
          role: docker
        exact_count: 1
        user_data: |
          #!/bin/bash
          TOWER={{tower_hostname}}
          JOB={{tower_provision_job_id}}
          KEY={{tower_hostkey}}
          EXTRA_VARS='{\"gitlab_root_password\": \"{{gitlab_root_password}}\", \"jenkins_admin_password\": \"{{jenkins_admin_password}}\", \"docker_admin_password\": \"{{docker_admin_password}}\", \"docker_repo_user\": \"{{docker_repo_user}}\", \"gitlab_private_key_id\": \"{{gitlab_private_key_id}}\", \"gitlab_user_token_id\": \"{{gitlab_user_token_id}}\", \"gitlab_public_key\": \"{{gitlab_public_key}}\", \"gitlab_private_key\": \"{{gitlab_private_key}}\"}'
          
          retry_attempts=10
          attempt=0
          while [[ $attempt -lt $retry_attempts ]]
          do
             status_code=`curl -s -i -k -H "Content-Type: application/json" --data '{"host_config_key":"${KEY}", "extra_vars":"${EXTRA_VARS}"}' http://${TOWER}/api/v1/job_templates/${JOB}/callback/ | head -n 1 | awk '{print $2}'`
             if [[ $status_code == 202 ]]
                 then
                 exit 0
             fi
             attempt=$(( attempt + 1 ))
             echo "${status_code} received... retrying in 1 minute. (Attempt ${attempt})"
             sleep 60
          done
          exit 1
      register: ec2
    - name: Wait for SSH to come up
      local_action: wait_for host="{{ item.public_ip }}" port=22 delay=5 timeout=1200
      with_items: '{{ec2.instances}}'
