---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    key_name: "Gitlab + Jenkins + Nexus"
    instance_type_light: t2.micro
    instance_type_heavy: t2.small
    security_group: sg-4b9f0b2d
    image: ami-d2c924b2
    region: us-west-2
    vpc_subnet_id: subnet-1832f040
    haproxy_reconfiguration_job: 32
  tasks:
    - name: Rescale Tomcat instances
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type_heavy }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          type: environment
          role: tomcat
          Name: Tomcat-Instance
        count_tag:
          role: tomcat
        exact_count: "{{ backends }}"
      register: ec2
    - meta: refresh_inventory
    - add_host: name=localhost
    - shell: 'curl -s -i -k -XPOST -H "Expect:" -H "Content-type: application/json" --user "admin:{{current_tower_password}}" "http://{{tower_hostname}}/api/v1/job_templates/{{haproxy_reconfiguration_job}}/launch/"'
      become: false
      delegate_to: localhost
