---
- hosts: tag_role_haproxy
  remote_user: centos
  ignore_errors: yes
  become: true
  tasks:
    - name: refresh inventory
      meta: refresh_inventory
    - name: recreate HAProxy config
      template: src=../configs/haproxy.cfg dest=/tmp/haproxy.cfg force=yes
    - name: activate HAProxy
      docker_container:
        name: haproxy
        image: "haproxy:1.6.7-alpine"
        restart: yes
        restart_policy: always
        hostname: "{{ ec2_public_dns_name }}"
        volumes:
          - /tmp/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
          - "443:443"
          - "80:80"
          - "2222:22"
    - debug: msg="HAProxy hostname is {{ ec2_public_dns_name }}"
    - wait_for: port=80 delay=10 timeout=1200
    - debug: msg="HAProxy frontend is up"
