---
- hosts: localhost
  connection: local
  become: no
  gather_facts: true
  vars:
    key_name: "Gitlab + Jenkins + Nexus"
    instance_type_light: t2.micro
    instance_type_heavy: t2.small
    security_group: sg-4b9f0b2d
    image: ami-d2c924b2
    region: us-west-2
    vpc_subnet_id: subnet-1832f040
    haproxy_reconfiguration_job: 32
    tomcat_reconfiguration_job: 35
  tasks:
    - name: Rescale Tomcat instances
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type_heavy }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          type: environment
          role: tomcat
          Name: Tomcat-Instance
        count_tag:
          role: tomcat
        exact_count: "{{ backends }}"
        volumes: 
          - device_name: /dev/sda1
            volume_size: 8
            delete_on_termination: true
      register: ec2
    - name: Wait for SSH to come up
      local_action: wait_for host="{{ item.public_ip }}" port=22 delay=5 timeout=1200
      with_items: '{{ec2.instances}}'
    - debug: msg="Instance {{ item.public_ip }} is up"
      with_items: '{{ec2.instances}}'
    - meta: refresh_inventory
    - add_host: name="{{ item.public_ip }}" group='tag_role_tomcat'
      with_items: '{{ec2.instances}}'
    - add_host: name=localhost
    - name: send HAProxy reconfiguration command
      local_action: shell 'curl -s -i -k -XPOST -H "Expect:" -H "Content-type: application/json" --user admin:{{current_tower_password}} http://localhost/api/v1/job_templates/{{haproxy_reconfiguration_job}}/launch/'
    - name: send Tomcat configuration command
      local_action: shell 'curl -s -i -k -XPOST -H "Expect:" -H "Content-type: application/json" --user admin:{{current_tower_password}} http://localhost/api/v1/job_templates/{{tomcat_reconfiguration_job}}/launch/'
