---
- hosts: localhost
  connection: local
  become: no
  gather_facts: true
  vars:
    key_name: "Gitlab + Jenkins + Nexus"
    instance_type_light: t2.micro
    instance_type_heavy: t2.small
    security_group: sg-4b9f0b2d
    image: ami-d2c924b2
    region: us-west-2
    vpc_subnet_id: subnet-1832f040
    haproxy_reconfiguration_job: 32
    tomcat_reconfiguration_job: 35
  tasks:
    - name: Rescale Tomcat instances
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type_heavy }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: 
          type: environment
          role: tomcat
          Name: Tomcat-Instance
        count_tag:
          role: tomcat
        exact_count: "{{ backends }}"
        volumes: 
          - device_name: /dev/sda1
            volume_size: 8
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          TOWER={{tower_hostname}}
          JOB={{tomcat_reconfiguration_job}}
          sleep 30
          retry_attempts=10
          attempt=0
          while [[ $attempt -lt $retry_attempts ]]
          do
             status_code=`curl -s -i -k -XPOST -H "Expect:" -H "Content-type: application/json" --user admin:{{current_tower_password}} http://${TOWER}/api/v1/job_templates/${JOB}/launch/ | head -n 1 | awk '{print $2}'`
             if [[ $status_code == 201 ]]
                 then
                 exit 0
             fi
             attempt=$(( attempt + 1 ))
             echo "${status_code} received... retrying in 1 minute. (Attempt ${attempt})"
             sleep 60
          done
          attempt=0
      register: ec2
    - name: Wait for SSH to come up
      local_action: wait_for host="{{ item.public_ip }}" port=22 delay=5 timeout=1200
      with_items: '{{ec2.instances}}'
    - debug: msg="Instance {{ item.public_ip }} is up"
      with_items: '{{ec2.instances}}'
    - meta: refresh_inventory
    - add_host: name="{{ item.public_ip }}" group='tag_role_tomcat'
      with_items: '{{ec2.instances}}'
    - uri:
        url: "http://{{tower_hostname}}/api/v1/job_templates/{{haproxy_reconfiguration_job}}/launch/"
        method: POST
        user: admin
        password: "{{current_tower_password}}"
        status_code: 201
        body_format: json
